# Site settings
title: "LJT Designs"
email: "hi@ljtdesigns.com"
description: ""
baseurl: "/"
url: "http://ljtdesigns.com"

# Build settings
markdown: kramdown
permalink: pretty

collections:
- designs
